version: '3'
services:
  lego-mongo:
    image: mongo
    container_name: lego-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - './mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    env_file:
      - .env
  lego-redis:
    image: redis:6
    container_name: lego-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    env_file:
      - .env
  lego-backend:
    depends_on:
      - lego-mongo
      - lego-redis
    image: registry.cn-shenzhen.aliyuncs.com/zhangyu586/lego:{{tag}}
    container_name: lego-backend
    ports:
     - 80:7001
    env_file:
      - .env